### PR TITLE
Update to BlmapChill v0180 (troll police)

### PR DESCRIPTION
**Pull request by ChillerDragon**
screenshot_2022-12-18_17-47-36

Entering police became waaay harder. Also a lot of trolling block spots. This is a super experimental update to bring some freshness and most of if not all of it should probably reverted at some point.

### CODE REVIEW

**Comment by ChillerDragon** [comment]
image

Force pushed edge suggested by fokko

**Comment by timofeycodes** [comment]
this shit is fucking gay

**Comment by WarHammer-z** [comment]
Screenshot_20221219-180836
Looks quite hard, it could be more easy

**Comment by ChillerDragon** [comment]
> Looks quite hard, it could be more easy

Yes its too hard and it will interrupt the current flow of the map and also break the police bot flappy.
But its more designed as an "event" version that won't be running for long.

**Comment by SoulyVEVO** [comment]
troll

**Comment by ChillerDragon** [comment]
screenshot_2022-12-23_17-38-11

Fix flag trap found by fokko

**Comment by fokkonaut** [comment]
LGTM

**Pull request merged**
