### PR TITLE
Update to BlmapChill v0184 (pvp island)

### LINKED ISSUE #48: Sun beams visible through the sun
Maybe hardly noticable but sun has different alpha values (none are set to 255) on each corner and because of that the sun beams are slightly going through the sun itself.
Not a big issue though.

### LINKED ISSUE #53: Make use of large boring area on the right of the spawn
screenshot_2021-03-31_13-57-01
Nothing but a long and repetitive path leading to a small island with farm tiles, i think that we could do something interesting with it.

### LINKED ISSUE #133: remove portal blocker tiles
it will be activated on hammer now using the same mechanic as spooky ghost.

### PR DESCRIPTION
**Pull request by ChillerDragon**
- remove portal blocker tiles (closed #133)
- make sun non transparent (closed #48)
- fix pvp gameplay on the island at the top right (closed #53)

screenshot_2023-11-05_11-50-02
screenshot_2023-11-05_11-51-28
screenshot_2023-11-05_11-50-08
screenshot_2023-11-05_11-50-13

### CODE REVIEW

**Comment by ChillerDragon** [comment]
I force pushed a little update. I finally fixed pvp in the following area. Which was a super frustrating spot to get stuck with an enemy if nobody has taser.

screenshot_2023-11-12_09-58-53


And then also added a way to drag enemys off the island. Otherwise one has to defend the dead corpses on that annoying island forever if a kill was made.

screenshot_2023-11-12_09-58-57

**Comment by cyberfig** [comment]
oh no chiller why

**Comment by ChillerDragon** [comment]
> oh no chiller why

?

**Comment by ChillerDragon** [comment]
Added changes requested by @fokkonaut 

image
image

Closed #114

**Comment by ChillerDragon** [comment]
@fokkonaut waiting for your ok c:

**Comment by fokkonaut** [comment]
I think this includes everything, not sure if we forgot something here. LGTM otherwise

**Pull request merged**
