### PR TITLE
Update to BlmapChill v0169 (fix block gp in race)

### PR DESCRIPTION
**Pull request by ChillerDragon**
Fix block gameplay in special race

Solves the issue of never ending groundhook bitch fights

screenshot_2022-06-06_08-29-59

### CODE REVIEW

**Comment by fokkonaut** [comment]
lgtm

**Comment by ChillerDragon** [comment]
screenshot_2022-06-06_14-29-22

**Comment by ChillerDragon** [comment]
screenshot_2022-06-06_14-42-16


Speedup force is 50.

**Comment by ChillerDragon** [comment]
screenshot_2022-06-06_14-50-06

screenshot_2022-06-06_14-50-08

The long over due spawn refactor. That turns it into an actual block map.

**Comment by ChillerDragon** [comment]
Closed by https://github.com/DDNetPP/maps/pull/100

**Pull request closed without merging**
