### PR TITLE
Update to BlmapChill v0175 (vip+ room & fixes)

### PR DESCRIPTION
**Pull request by fokkonaut**
Fix flying bush with HD off
image

Fix missing freeze at spawn in wall
image

Place taser in these 2 spots for now (maybe a third one aswell, but i think at 5jumps for example is too op/fast?)
image
image

VIP+ room
image

### CODE REVIEW

**Comment by ChillerDragon** [comment]
Yea looks good. Not sure about taser being so hard to reach. I would love to delay taser nerf until other bonuses are even more rare. Like infjumps, jetpack, 8jumps. This forces taser players to spend more time in the race than actually blocking. Some would probably say thats a good thing but imo thats boring for both parties. The attacker spending all day in race and the defender in police getting bored. If its harder to get taser it will get harder to kill full bonus players which are less a thing but still exist.

**Comment by fokkonaut** [comment]
Im open to add another taser somewhere, I was just not sure where

**Comment by fokkonaut** [comment]
image

**Comment by fokkonaut** [comment]
Fixes #110

**Pull request merged**
